### ISSUE TITLE
Erro ao Criar o Produto

### ISSUE THREAD

**Issue by pauloneda** [Trust-Code/odoo-brazil-eletronic-documents#13]
nfe/nfe_import/models/nfe_import_edit.py", line 258, in product_create
    return product_tmpl.product_variant_ids[0]
  File "/opt/odoo/odoo/openerp/models.py", line 5644, in **getitem**
    return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range

**Comment by danimaribeiro** [comment]
Tem algum produto sem variante cadastrado no banco?

**Comment by pauloneda** [comment]
Até então não tinha, 
ao tentar importar criou um produto sem variante, porém fui na categoria e habilitei a criação automática das variantes, ai criou o produto certinho.

**Comment by danimaribeiro** [comment]
Vou fechar este bug, pois originalmente no Odoo todo produto tem pelo menos uma variante.
