### ISSUE TITLE
módulo Trust-Code/odoo-brazil-eletronic-documents dando BUG

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brazil-eletronic-documents#24]
Quando uso o módulo odoo-brazil-eletronic-documents da Trust-Code o layout da interface do odoo nem chega a abrir. Quando uso o que está na odoo-brasil não buga.

Alguma orientação sobre o problema?

**Comment by ghost** [comment]
Solução!
apt-get remove python-suds
apt-get remove --auto-remove python-suds
pip install suds_requests

Irei fazer mais testes e ter certeza se a solução não teve alguma consequência.

**Comment by danimaribeiro** [comment]
É isso mesmo
