### ISSUE TITLE
Dúvida sobre implantação

### ISSUE THREAD

**Issue by izaguerreiro** [Trust-Code/odoo-brazil-eletronic-documents#28]
Bom dia, 

Estou iniciando a implantação do Odoo na empresa que trabalho e teremos que utilizar a NF-e, porém não encontrei em nenhum lugar alguma documentação que explicasse como adicionar este módulo no sistema.
Vocês poderiam me ajudar, por favor?

Desde já, obrigada

**Comment by danimaribeiro** [comment]
Recomendo usar esta versão.
https://github.com/Trust-Code/odoo-brasil

Aqui tem um tutorial para desenvolvedores.
http://www.trustcode.com.br/blog/seu-blog-1/post/instalando-o-odoo-10-3

Caso precise de suporte pode entrar em contato com nossa empresa.

**Comment by izaguerreiro** [comment]
Obrigada pela ajuda.
